/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppGallery {}
  interface AppGalleryAttributes extends StencilHTMLAttributes {}

  interface AppWordCount {
    'placeholder': string;
  }
  interface AppWordCountAttributes extends StencilHTMLAttributes {
    'placeholder'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppGallery': Components.AppGallery;
    'AppWordCount': Components.AppWordCount;
  }

  interface StencilIntrinsicElements {
    'app-gallery': Components.AppGalleryAttributes;
    'app-word-count': Components.AppWordCountAttributes;
  }


  interface HTMLAppGalleryElement extends Components.AppGallery, HTMLStencilElement {}
  var HTMLAppGalleryElement: {
    prototype: HTMLAppGalleryElement;
    new (): HTMLAppGalleryElement;
  };

  interface HTMLAppWordCountElement extends Components.AppWordCount, HTMLStencilElement {}
  var HTMLAppWordCountElement: {
    prototype: HTMLAppWordCountElement;
    new (): HTMLAppWordCountElement;
  };

  interface HTMLElementTagNameMap {
    'app-gallery': HTMLAppGalleryElement
    'app-word-count': HTMLAppWordCountElement
  }

  interface ElementTagNameMap {
    'app-gallery': HTMLAppGalleryElement;
    'app-word-count': HTMLAppWordCountElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
